/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AddCardFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AddPointsFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UpdateUserFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Web": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "liam-api-323": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "liam-app-api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "liam-app-user-pool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "liam-app-web-artifacts": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "liam-table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}